# Generated by Django 3.2.5 on 2021-12-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
            ],
        ),
    ]
